version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0

  your_app:
    build: ./your_app_directory
    volumes:
      - ./your_app_directory:/app
    depends_on:
      - redis
